### ISSUE TITLE
policy-controller unit erroring

### ISSUE THREAD

**Issue by rossf7** [giantswarm/k8scloudconfig#91]
The unit starts but logs the error

```
May 08 11:18:41 ip-10-0-133-111.eu-west-1.compute.internal docker[3002]: TypeError: object of type 'NoneType' has no len()
May 08 11:18:41 ip-10-0-133-111.eu-west-1.compute.internal docker[3002]: 2017-05-08 11:18:41,628 6 WARNING Re-starting watch on resource: NetworkPolicy
```

**Comment by puja108** [comment]
Full error for context:

```2017-05-08 13:36:23,015 6 WARNING Re-starting watch on resource: NetworkPolicy
2017-05-08 13:36:24,015 6 INFO Syncing 'NetworkPolicy' objects
2017-05-08 13:36:24,028 6 ERROR Unahandled exception killed NetworkPolicy manager
Traceback (most recent call last):
  File "<string>", line 283, in _manage_resource
  File "<string>", line 388, in _sync_resources
TypeError: object of type 'NoneType' has no len()```

**Comment by puja108** [comment]
The error we are having with it is benign, it just happens if there’s no policies from the api server (as we didn’t set any): https://github.com/projectcalico/k8s-policy/issues/63

It is fixed in future versions but no need to hunt, I’ll close the issue.
